/*
 * The MIT License
 *
 * Copyright 2018 André H. Juffer, Biocenter Oulu
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

package org.bco.cm.dto;

import java.util.UUID;
import java.io.Serializable;
import java.util.Objects;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Id;
import javax.persistence.GeneratedValue;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

/**
 *
 * @author Andr&#233; H. Juffer, Biocenter Oulu
 */
@Entity( name = "ChoiceDTO" )
@Table( name = "choices" )
public class ChoiceDTO implements Serializable {
    
    private UUID id_;
    private String phrase_;
    private MultipleChoiceQuestionDTO parent_;
    
    public ChoiceDTO()
    {
        id_ = null;
        phrase_ = null;
        parent_ = null;
    }
    
    public ChoiceDTO(String phrase)
    {
        this();
        phrase_ = phrase;
    }

    private void setId(UUID id)
    {
        id_ = id;
    }
    
    /**
     * Returns identifier assigned or generated by repository.
     * @return Identifier.
     */
    @Id
    @GeneratedValue
    protected UUID getId()
    {
        return id_;
    }       
    
    public void setPhrase(String phrase)
    {
        phrase_ = phrase;
    }
    
    @Column( name = "phrase" )
    public String getPhrase()
    {
        return phrase_;
    }
    
    protected void setParentMultipleChoiceQuestion(MultipleChoiceQuestionDTO parent)
    {
        parent_ = parent;
    }
    
    @ManyToOne()
    @JoinColumn( name = "multiple_choice_question_id" )
    protected MultipleChoiceQuestionDTO getParentMultipleChoiceQuestion()
    {
        return parent_;
    }
    
    @Override
    public String toString()
    {
        String newline = System.getProperty("line.separator");
        StringBuilder s = new StringBuilder("ChoiceDTO : {").append(newline);
        s.append("phrase - ").append(phrase_).append(newline);
        s.append("}");
        return s.toString();
    }
    
    @Override
    public boolean equals(Object other)
    {
        if ( other == null ) {
            return false;
        }
        if ( this == other ) {
            return true;
        }
        if ( !(this.getClass().equals(other.getClass())) ) {
            return false;
        }
        final ChoiceDTO choice = (ChoiceDTO)other;
        return phrase_.equals(choice.getPhrase());        
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 23 * hash + Objects.hashCode(this.phrase_);
        return hash;
    }
    
}
