/*
 * The MIT License
 *
 * Copyright 2018 André H. Juffer, Biocenter Oulu
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

package org.bco.cm.dto;

import java.util.UUID;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.hibernate.annotations.NaturalId;
import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * DTO for OnlineMaterial.
 * @author Andr&#233; H. Juffer, Biocenter Oulu
 */
@Entity( name = "OnlineMaterialDTO" )
@Table( name = "online_materials" )

public class OnlineMaterialDTO {
    
    private UUID id_;
    private int materialId_;
    private String content_;
    
    private LearningPathDTO learningPath_;
    
    public OnlineMaterialDTO()
    {
        id_ = null;
        materialId_ = 0;
        content_ = null;
        learningPath_ = null;
    }
    
    private void setId(UUID id)
    {
        id_ = id;
    }
    
    /**
     * Returns identifier as generated by repository.
     * @return Identifier value.
     */
    @Id
    @GeneratedValue
    protected UUID getId()
    {
        return id_;
    }

    public void setMaterialId(int id)
    {
        materialId_ = id;
    }
    
    @Column( name = "material_id" )
    @NaturalId
    public int getMaterialId()
    {
        return materialId_;
    }
    
    public void setContent(String content)
    {
        content_ = content;
    }
    
    @Column( name = "content" )
    public String getContent()
    {
        return content_;
    }
    
    public void setLearningPath(LearningPathDTO learningPath)
    {
        learningPath_ = learningPath;
    }
    
    @ManyToOne
    @JoinColumn( name = "learning_path_id" )
    @JsonIgnore
    public LearningPathDTO getLearningPath()
    {
        return learningPath_;
    }
    
    @Override
    public String toString()
    {
        String newline = System.getProperty("line.separator");
        StringBuilder s = new StringBuilder("OnlineMaterialDTO : {").append(newline);
        s.append("materialId - ").append(materialId_).append(newline);
        s.append("content - ").append(content_).append(newline);
        s.append("}");
        return s.toString();
    }

}
