/*
 * The MIT License
 *
 * Copyright 2018 André H. Juffer, Biocenter Oulu
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

package org.bco.cm.dto;

import java.io.Serializable;
import java.util.UUID;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DTO for StudentMonitor.
 * @author Andr&#233; H. Juffer, Biocenter Oulu
 */
@Entity( name = "StudentMonitorDTO" )
@Table( name = "student_monitors" )
public class StudentMonitorDTO implements Serializable {
    
    private UUID id_;
    private int monitorId_;    
    private String studentId_;
    private String enrolmentNumber_;
    private int currentModuleId_;
    
    private void setId(UUID id)
    {
        id_ = id;
    }
    
    /**
     * Returns identifier generated by repository.
     * @return Identifier.
     */
    @Id
    @GeneratedValue
    protected UUID getId()
    {
        return id_;
    }
    
    public void setMonitorId(int monitorId)
    {
        monitorId_ = monitorId;
    }
    
    @Column( name = "monitor_id" )
    public int getMonitorId()
    {
        return monitorId_;
    }
    
    public void setStudentId(String studentId)
    {
        studentId_ = studentId;
    }
    
    @Column( name = "student_id" )
    public String getStudentId()
    {
        return studentId_;
    }
    
    public void setCurrentModuleId(int currentModuleId)
    {
        currentModuleId_ = currentModuleId;
    }
    
    @Column( name = "current_module_id" )
    public int getCurrentModuleId()
    {
        return currentModuleId_;
    }
    
    public void setEnrolmentNumber(String enrolmentNumber)
    {
        enrolmentNumber_ = enrolmentNumber;
    }
    
    @Column( name = "enrolment_number" )
    public String getEnrolmentNumber()
    {
        return enrolmentNumber_;
    }
    
    @Override
    public String toString()
    {
        String newline = System.getProperty("line.separator");
        StringBuilder s = new StringBuilder("StudentMonitorDTO : {").append(newline);
        s.append("monitorId - ").append(monitorId_).append(newline);
        s.append("studentId - ").append(studentId_).append(newline);       
        s.append("enrolmentNumber - ").append(enrolmentNumber_).append(newline);
        s.append("currentModuleId - ").append(currentModuleId_).append(newline);
        s.append("}");
        return s.toString();
    }

}
