/*
 * The MIT License
 *
 * Copyright 2018 André H. Juffer, Biocenter Oulu
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

package org.bco.cm.domain.course;

import com.tribc.cqrs.util.EventUtil;
import com.tribc.ddd.domain.event.Event;
import com.tribc.ddd.domain.event.Eventful;
import java.io.Serializable;
import java.time.Instant;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Random;
import java.util.UUID;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Embedded;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.MapKey;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;
import org.bco.cm.domain.course.event.NewCourseAddedToCatalog;
import org.bco.cm.dto.CourseDescriptionDTO;
import org.bco.cm.dto.ModuleDTO;
import org.bco.cm.util.Identifiable;
import org.hibernate.annotations.NaturalId;

/**
 * An unit of teaching that typically lasts one academic term. The course 
 * description consists of a title, summary, and separate components or modules 
 * that are taken in a sequential order by students.
 * @author Andr&#233; H. Juffer, Biocenter Oulu
 */
@Entity( name="CourseDescription" )
@Table( name = "course_descriptions" )
public class CourseDescription implements Eventful, Identifiable, Serializable {
    
    // For generating module identifiers that are unique to a given course.
    private final static Random RANDOM;
    
    static {
        RANDOM = new Random();
        RANDOM.setSeed(Instant.now().toEpochMilli());
    }
    
    private UUID id_;
    private CourseId courseId_;
    private String title_;
    private String summary_;
    private Map<Integer,Module> modules_;
    private Module firstModule_;
    private int firstModuleId_;
    private TeacherId teacherId_;
    
    private final Collection<Event> events_;
    
    protected CourseDescription()
    {
        courseId_ = null;
        title_ = null;
        summary_ = null;
        modules_ = new HashMap<>();
        firstModule_ = null;
        firstModuleId_ = -1;
        teacherId_ = null;
        events_ = new HashSet<>();
    }
    
    private void setId(UUID id)
    {
        id_ = id;
    }
    
    /**
     * Returns identifier generated by repository.
     * @return Identifier.
     */
    @Id
    @GeneratedValue
    protected UUID getId()
    {
        return id_;
    }
    
    private void setIdentifier(CourseId courseId)
    {
        if ( courseId == null ) {
            throw new NullPointerException("Missing course identifier.");
        }
        courseId_ = courseId;
    }
    
    /**
     * Returns course identifier.
     * @return Identifier. Never null.
     */
    @Transient
    public CourseId getIdentifier()
    {
        return courseId_;
    }
    
    private void setCourseId(CourseId courseId)
    {
        this.setIdentifier(courseId);
    }
    
    /**
     * Returns course identifier.
     * @return Course identifier. Never null.
     */
    @NaturalId
    @Embedded
    public CourseId getCourseId()
    {
        return this.getIdentifier();
    }

    @Override
    @Transient
    public String getIdentifierAsString() 
    {
        return courseId_.stringValue();
    }
    
    private void setTitle(String title)
    {
        if ( title == null ) {
            throw new NullPointerException("Missing course title.");
        }
        if ( title.isEmpty() ) {
            throw new IllegalArgumentException("Empty course title.");
        }
        title_ = title;
    }
    
    /**
     * Returns course title.
     * @return Title. Never null or empty.
     */
    @Column( name = "title")
    public String getTitle()
    {
        return title_;
    }
    
    private void setSummary(String summary)
    {
        if ( summary == null ) {
            throw new NullPointerException("Missing course summary.");
        }
        if ( summary.isEmpty() ) {
            throw new IllegalArgumentException("Empty course summary.");
        }
        summary_ = summary;
    }
    
    /**
     * Return course summary.
     * @return Summary. Never null or empty.
     */
    @Column( name = "summary")
    public String getSummary()
    {
        return summary_;
    }
    
    private void setModules(Map<Integer,Module> modules)
    {        
        if ( modules_ == null ) {
            throw new NullPointerException("Missing course modules.");
        }
        modules_ = modules;
        modules_.values().forEach(module -> {
            module.setCourseDescription(this);
        });
        this.setFirstModuleId(firstModuleId_);
    }

    @OneToMany( 
        mappedBy = "courseDescription", 
        cascade = CascadeType.ALL, 
        orphanRemoval = true 
    )
    @MapKey( name = "moduleId" )
    protected Map<Integer,Module> getModules()
    {
        return modules_;
    }
    
    /**
     * Returns course modules.
     * @return Unmodifiable list of modules. Never null. May be empty.
     */
    public List<Module> modules()
    {
        return Collections.unmodifiableList(new ArrayList<>(modules_.values()));
    }
    
    private void setFirstModule(Module first)
    {
        firstModule_ = first;
        if ( firstModule_ != null ) {
            firstModule_.setCourseDescription(this);
            firstModuleId_ = firstModule_.getModuleId();
        }
    }
    
    @Transient
    Module getFirstModule()
    {
        return firstModule_;
    }
    
    private void setFirstModuleId(int firstModuleId)
    {
        firstModuleId_ = firstModuleId;
        if ( !modules_.isEmpty() && firstModuleId > 0 ) {
            firstModule_ = modules_.get(firstModuleId_);
        }
    }
    
    /**
     * Returns the identifier of the first module of this course.
     * @return Identifier value or -1 if th first module is not set.
     */
    @Column( name = "first_module_id" )
    protected int getFirstModuleId()
    {
        if ( firstModule_ != null ) {
            return firstModule_.getModuleId();
        } else {
            return -1;
        }
    }
    
    private void setTeacherId(TeacherId teacherId)
    {
        if ( teacherId == null ) {
            throw new NullPointerException("Missing teacher for course.");
        }
        teacherId_ = teacherId;
    }
    
    @Embedded
    protected TeacherId getTeacherId()
    {
        return teacherId_;
    }
    
    /**
     * Creates a new course description.
     * @param teacher Responsible teacher.
     * @param courseId New course identifier.
     * @param spec New course specification. Must include title and summary, no
     * modules.
     * @return New course description.
     * @see #addModule(org.bco.cm.dto.ModuleDTO) 
     */
    public static CourseDescription valueOf(Teacher teacher, 
                                            CourseId courseId,
                                            CourseDescriptionDTO spec)
    {
        if ( teacher == null ) {
            throw new NullPointerException("Missing new course teacher.");
        }
        if ( spec == null ) {
            throw new NullPointerException("Missing new course specification.");
        }
        CourseDescription course = new CourseDescription();
        course.setCourseId(courseId);
        course.setTeacherId(teacher.getTeacherId());
        course.setSummary(spec.getSummary());
        course.setTitle(spec.getTitle());
        return course;
    }
    
    /**
     * Updates course description.
     * @param spec Course update specification. Title and summary only.
     */
    public void update(CourseDescriptionDTO spec)
    {
        this.setSummary(spec.getSummary());
        this.setTitle(spec.getTitle());
    }
    
    /**
     * Returns a data transfer object.
     * @return DTO.
     */
    public CourseDescriptionDTO toDTO()
    {
        CourseDescriptionDTO dto = new CourseDescriptionDTO();
        dto.setCourseId(courseId_.stringValue());
        dto.setSummary(summary_);
        dto.setTitle(title_);
        dto.setAllModules(Module.toDTOs(modules_.values()));
        if ( this.hasModules() ) {
            dto.setFirstModule(this.getFirstModule().toDTO());        
        }
        dto.setTeacherId(teacherId_.stringValue());
        return dto;
    }
    
    /**
     * Adds new module to this course.
     * @param spec New module specification. This module is appended to the last
     * module.
     */
    public void addModule(ModuleDTO spec)
    {
        if ( spec == null ) {
            throw new NullPointerException(
                "Trying to add an undefined module to course."
            );
        }
                
        // Create new module according to specification.
        int moduleId = this.generateModuleId();
        Module next = Module.valueOf(moduleId, spec);
        next.setCourseDescription(this);
        
        // The new module becomes the first module of this course, if no other modules
        // are present.
        if ( this.hasModules() ) {
            Module last = this.lastModule();
            last.setNext(next);
        } else {
            this.setFirstModule(next);
        }
        
        // Save new module.
        modules_.put(moduleId, next);
    }
    
    
    private boolean hasModules()
    {
        return !modules_.isEmpty();
    }
    
    private Module firstModule()
    {
        if ( modules_.isEmpty() ) {
            throw new IllegalStateException("No modules specified for course.");
        }
        return this.getFirstModule();
    }
    
    private Module lastModule()
    {
        if ( modules_.isEmpty() ) {
            throw new IllegalStateException("No modules specified for course.");
        }
        Module current = this.firstModule();
        while ( current.hasNext() ) {
            current = current.getNext();
        }
        return current;
    }
    
    /**
     * Finds module.
     * @param moduleId Module identifier value.
     * @return Module or null if nonexistent.
     */
    Module findModule(int moduleId)
    {
        if ( moduleId > 0 && !modules_.isEmpty() ) {
            return modules_.get(moduleId);
        } else {
            return null;
        }
    }

    /**
     * Returns identifier only unique in context of this course.
     * @return Identifier. This value is in the interval 
     * &lt;0, Integer.MAX_VALUE - 100]. 
     */
    private int generateModuleId()
    {
        int bound = Integer.MAX_VALUE - 100;
        int id = RANDOM.nextInt(bound);
        while ( modules_.containsKey(id) ) {
            id = RANDOM.nextInt(bound) + 1;
        }
        return id;
    }

    @Override
    @Transient
    public Collection<Event> getEvents() 
    {
        return EventUtil.selectUnhandled(events_);
    }

    @Override
    public void clearEvents() 
    {
        events_.clear();
    }
    
    @Override
    public boolean equals(Object other)
    {
        if ( this == other ) {
            return true;
        }
        if ( other == null || this.getClass() != other.getClass() ) {
            return false;
        }
        CourseDescription course = (CourseDescription)other;
        return this.getCourseId().equals(course.getCourseId());
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 47 * hash + Objects.hashCode(this.id_);
        hash = 47 * hash + Objects.hashCode(this.courseId_);
        hash = 47 * hash + Objects.hashCode(this.title_);
        hash = 47 * hash + Objects.hashCode(this.summary_);
        hash = 47 * hash + Objects.hashCode(this.modules_);
        hash = 47 * hash + Objects.hashCode(this.firstModule_);
        hash = 47 * hash + this.firstModuleId_;
        hash = 47 * hash + Objects.hashCode(this.teacherId_);
        return hash;
    }
    
    /**
     * Signals this course is newly to course catalog.
     */
    void addedToCourseCatalog()
    {
        this.events_.add(new NewCourseAddedToCatalog(this));
    }
    
    
}
