/*
 * The MIT License
 *
 * Copyright 2017 André H. Juffer, Biocenter Oulu.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

package org.bco.cm.domain.student;

import com.tribc.cqrs.util.EventUtil;
import com.tribc.ddd.domain.event.Event;
import com.tribc.ddd.domain.event.Eventful;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Collection;
import java.util.HashSet;
import java.util.List;
import java.util.UUID;
import javax.persistence.Embedded;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import org.bco.cm.domain.student.event.NewStudentRegistered;
import org.bco.cm.dto.StudentDTO;
import org.bco.cm.util.Person;
import org.hibernate.annotations.NaturalId;

/**
 * Course participant.
 * @author André H. Juffer, Biocenter Oulu
 */
@Entity(name = "Student")
@Table(name = "students")
public class Student extends Person<StudentId> implements Eventful, Serializable {
    
    private UUID id_;
    
    private final Collection<Event> events_;
    
    protected Student()
    {
        super();
        id_ = null;
        events_ = new HashSet<>();
    }
    
    private void setId(UUID id)
    {
        id_ = id;
    }
    
    /**
     * Returns identifier generated by repository.
     * @return Identifier.
     */
    @Id
    @GeneratedValue
    protected UUID getId()
    {
        return id_;
    }
    
    private void setStudentId(StudentId studentId)
    {
        this.setIdentifier(studentId);
    }
    
    /**
     * Returns student identifier. This identifier is provided by the
     * client application.
     * @return Student identifier.
     */
    @NaturalId
    @Embedded
    public StudentId getStudentId()
    {
        return this.getIdentifier();
    }
    
    /**
     * Creates new student.
     * @param studentId New student identifier. Must not be null.
     * @param spec New student specification. Must not be null. Must hold 
     * first name and surname.
     * @return Newly created student.
     */
    public static Student valueOf(StudentId studentId, StudentDTO spec)
    {
        if ( spec == null ) {
            throw new NullPointerException("Missing new student specification.");
        }
        Student student = new Student();
        student.setIdentifier(studentId);
        student.setFirstName(spec.getFirstName());
        student.setSurname(spec.getSurname());
        return student;
    }
    
    /**
     * Returns data transfer object representation.
     * @return DTO
     */
    public StudentDTO toDTO()
    {
        StudentDTO dto = new StudentDTO();
        this.populateDTO(dto);
        return dto;
    }
    
    /**
     * Returns DTO collection.
     * @param students Students.
     * @return DTOs.
     */
    public static List<StudentDTO> toDTOs(Collection<Student> students)
    {
        List<StudentDTO> dtos = new ArrayList<>();
        students.forEach((student) -> {
            dtos.add(student.toDTO());
        });
        return dtos;
    }
    
    @Override
    @Transient
    public Collection<Event> getEvents() 
    {
        return EventUtil.selectUnhandled(events_);
    }

    @Override
    public void clearEvents() 
    {
        events_.clear();
    }
    
    /**
     * Signals that this student is newly registered.
     */
    void registered()        
    {
        events_.add(new NewStudentRegistered(this));
    }
}
